### ISSUE TITLE
Add standard combat mode concepts (time limit, rebalance xp, late join xp)

### ISSUE THREAD

**Issue by MysteriousMilk** [MysteriousMilk/NS2_CombatPlusPlus#40]
- [ ] Add round time limit
- [ ] Add overtime concept (welding/healing disabled)
- [ ] Re-balance xp across the team "every so often"
- [ ] Auto-level late joining players
- [ ] Add penalty for players that leave and rejoin
