### ISSUE TITLE
Implement Combat++ Progression System

### ISSUE THREAD

**Issue by MysteriousMilk** [MysteriousMilk/NS2_CombatPlusPlus#5]
- [x] Create new mixin to track xp, rank and skill points
- [x] Award XP for Kills
- [x] Award XP for Assists
- [x] Award XP for doing Damage
- [x] Award XP for Building
- [x] Award XP for Welding (Marines)
- [x] Award XP for Healing (Aliens)
- [x] Award Skill Point on Level Up
- [x] Award Skill Point for 'Rampage' criteria
- [x] Award Skill Point for 'Got Your Back' criteria
- [x] Award Skill Point for 'Damage Dealer' criteria
- [x] Update Marine HUD to show Progression and Skill Points
- [x] Update Alien HUD to show Progression and Skill Points
- [x] Visual Indicators for XP Earned
- [x] Add XP Scaling based on distance from enemy tech point

**Comment by MysteriousMilk** [comment]
Progression system is essentially done.  Since all upgrades are going to become persistent and the player can respec, there is no longer a need to award additional skill points outside of leveling up.  Instead, the special criteria (rampage, got your back, damage dealer, healer, carpenter, etc) will just be awarded a bit of xp.
