### ISSUE TITLE
Marine Buy Menu

### ISSUE THREAD

**Issue by MysteriousMilk** [MysteriousMilk/NS2_CombatPlusPlus#6]
Marines purchase weapons, upgrades and structures from a buy menu (accessed by pressing the 'Buy' key on the keyboard) instead of the armory, proto lab, etc.

- [x] Create Marine Buy Menu GUI
- [x] Enable Marine Buy menu via the 'Buy' key
- [x] Allow Weapons to be purchased from the Marine Buy Menu
- [x] Allow Upgrades to be purchased from the Marine Buy Menu
- [x] Allow Structures to be purchased from Marine Buy Menu
- [x] Allow Tech to be purchased from the Marine Buy Menu
- [x] Allow Consumables to be purchased from the Marine Buy Menu

**Comment by MysteriousMilk** [comment]
Tech stuff should be working, just need to test.  Only thing left to do is get the consumables working.

**Comment by MysteriousMilk** [comment]
Consumables now work on cool downs.  Tested all the stuff on the Marine buy menu.  Seems to be working fine.
